reposRoot: "repos"
dbRoot: ".db"
dbCacheSize: 1024

authorsFile: "authorsFile.txt"
logWindowsSize: 10000

systemGitUserName: "Git Svn Bridge"
osGitUserName: "bridge-admin"
commitMessageFormat: "%B"

logFile: "errors.log"